export const ITEMS = [
    {
        id: 1,
        name: "root beer",
        img: "assets/jovial.png",
        content: "slow-5",
        msg: "glup glup glup",
        desc: "Mug. (+5s)",
        cost: 3,
        stock: 5
    },
    {
        id: 2,
        name: "treasure buster",
        img: "assets/jovial.png",
        content: "reward-15",
        modName: "▲ reward",
        msg: "Busting some treasure...",
        desc: "Good investment. (+$15 reward)",
        cost: 10,
        stock: 2,
    },
    {
        id: 3,
        name: "dice",
        img: "assets/jovial.png",
        content: "rewardChance-3",
        modName: "▲ reward chance",
        msg: "You rolled the dice...",
        desc: "Gamble (+70% reward chance)",
        cost: 15,
        stock: 4
    },
    {
        id: 4,
        name: "joker card",
        img: "assets/jovial.png",
        content: "slow-60_multSet-1",
        msg: "You played the joker card.",
        desc: "Balatro...? (+60s time, reset mult)",
        cost: 30,
        stock: 2
    },
    {
        id: 5,
        name: "celsius",
        img: "assets/jovial.png",
        content: "slow-5_addStartTime-5",
        msg: "You drank the celsius, you feel energized..",
        desc: "Unhealthy energy drink (+5s, +5s start)",
        cost: 40,
        stock: 5
    },
    {
        id: 6,
        name: "super root beer",
        img: "assets/jovial.png",
        content: "slow-30_multAdd-1",
        msg: "glup glup glup SUPER",
        desc: "Even better mug (+30s time, +1 mult)",
        cost: 80,
        stock: 4
    },
    {
        id: 7,
        name: "dictionary",
        img: "assets/jovial.png",
        content: "solvePuzzle-na",
        msg: "You read the dictionary.",
        desc: "Search up every word (Clear board)",
        cost: 100,
        stock: 1
    },
    {
        id: 8,
        name: "super duper root beer",
        img: "assets/jovial.png",
        content: "addStartTime-60_multAdd-3_livesSet-99",
        msg: "glup super super super",
        desc: "Super root beer (???)",
        cost: 9999,
        stock: 1
    },
    {
        id: 9,
        name: "the whisperer",
        img: "assets/jovial.png",
        content: "whisperer-na",
        msg: null,
        desc: "he may help you.. (select a word)",
        cost: 30,
        stock: 1
    },
    {
        id: 10,
        name: "potato pancake",
        img: "assets/jovial.png",
        content: "addStartTime-10",
        msg: "yum yum C:",
        desc: "delicious potato pancakes (+10s start)",
        cost: 40,
        stock: 3
    },
    {
        id: 11,
        name: "cocktail",
        img: "assets/jovial.png",
        content: "addStartTime-1_slow-10_multAdd-1_rewardChance-4",
        modName: "▲ reward chance",
        msg: "buuuurp",
        desc: "furious cocktail of 4 effects (+1s start, +10s, +1 mult, +60% reward chance)",
        cost: 60,
        stock: 1,
    },
    {
        id: 12,
        name: "firework",
        img: "assets/jovial.png",
        content: "fillRandomLetters-5",
        msg: "boom",
        desc: "explosion of letters",
        cost: 20,
        stock: 3
    },
    {
        id: 13,
        name: "brisk iced tea",
        img: "assets/jovial.png",
        content: "freezeStreak-1",
        msg: "",
        desc: "cold.. (+1 Streak Freeze)",
        cost: 25,
        stock: 1
    },
    {
        id: 14,
        name: "peanut butter",
        img: "assets/jovial.png",
        content: "livesSet-1",
        msg: "You feel sticky",
        desc: "yummy peanut butter (+1 life)",
        cost: 50,
        stock: 2
    },
    {
        id: 15,
        name: "sandwich",
        img: "assets/jovial.png",
        content: "livesSet-2",
        msg: "yummers",
        desc: "filling tuna sandwich (+2 lives)",
        cost: 115,
        stock: 1
    },
    {
        id: 16,
        name: "golden apple",
        img: "assets/jovial.png",
        content: "maxLivesSet-1",
        msg: "nom nom nom :D",
        desc: "enchanted apple that grants more health (+1 max lives)",
        cost: 130,
        stock: 1
    },
    {
        id: 17,
        name: "enchanted golden apple",
        img: "assets/jovial.png",
        content: "maxLivesSet-1_livesSet-3",
        msg: "chomp",
        desc: "legendary apple with regenerative abilities. (+1 max, +3 lives)",
        cost: 240,
        stock: 1,
    },
    {
        id: 18,
        name: "omers curse",
        img: "assets/jovial.png",
        content: "damageAdd-1_multAdd-1",
        msg: "You feel the wrath.",
        desc: "Double jeopardy. (+1 dmg, +1 mult)",
        cost: 80,
        stock: 1,
    }
]
